spring:
  application:
    name: notification-service
  profiles:
    active: local

server:
  port: 8086
  servelt:
    context-path: /notification

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
