spring:
  application:
    name: inventory-service
  profiles:
    active: local

server:
  port: 8082
  servelt:
    context-path: /inventory

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
